<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup>
        <BlenderAddonDir>F:\dev0\prjk\Smoothie\Blender Addon\lib</BlenderAddonDir>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="SkiaSharp" Version="4.150.1" />
      <PackageReference Include="WolvenKit.Common" Version="8.19.0" />
      <PackageReference Include="WolvenKit.Core" Version="8.19.0" />
      <PackageReference Include="WolvenKit.Modkit" Version="8.19.0" />
      <PackageReference Include="WolvenKit.RED4" Version="8.19.0" />
    </ItemGroup>
    
    <Target Name="CopyToBlender" AfterTargets="Build">
        <ItemGroup>
            <FilesToCopy Include="$(TargetDir)*.*" />
        </ItemGroup>

        <Copy
                SourceFiles="@(FilesToCopy)"
                DestinationFolder="$(BlenderAddonDir)"
                SkipUnchangedFiles="true" />
    </Target>
    
</Project>
